name: hopeful_bamboo
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.16.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  animated_text_kit: ^4.2.1
  audioplayers: ^0.20.1
  video_player: ^2.2.18
  url_launcher: ^6.0.20
  share_plus: ^3.1.0
  animations: ^2.0.2
  flutter_animator: ^3.2.1
  animate_do: ^2.1.0
  simple_gesture_detector: ^0.2.0
  carousel_slider: ^4.0.0


dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:

  uses-material-design: true

  assets:
    - assets/icons/
    - assets/images/
    - assets/sound/
    - assets/video/

  fonts:
    - family: RobotoSlab
      fonts:
        - asset: assets/fonts/RobotoSlab-Regular.ttf
          weight: 400
        - asset: assets/fonts/RobotoSlab-Light.ttf
          weight: 300
    - family: BebasNeue
      fonts:
        - asset: assets/fonts/BebasNeue.ttf
